# .github/workflows/main-chemfyi-workflow.yml

name: Run ChemFYI

on:
  pull_request:
  workflow_dispatch:

jobs:
  # This job will call the reusable workflow multiple times in parallel
  dispatch-runs:
    # Use the reusable workflow file
    uses: ./.github/workflows/reusable-chemfyi-run.yml
    
    # Pass the required secret to the reusable workflow
    secrets: inherit

    # Define a matrix of parameters for each job run
    strategy:
      fail-fast: false # Allows other jobs to continue even if one fails
      matrix:
        include:
          - { start: 1,    end: 2000,  artifact: "extracted_sigma_aldrich" }
          - { start: 2001, end: 4000,  artifact: "extracted_sigma_aldrich2" }
          - { start: 4001, end: 6000,  artifact: "extracted_sigma_aldrich3" }
          - { start: 6001, end: 8000,  artifact: "extracted_sigma_aldrich4" }
          - { start: 8001, end: 10000, artifact: "extracted_sigma_aldrich5" }
          - { start: 10001, end: 12000, artifact: "extracted_sigma_aldrich6" }
          - { start: 12001, end: 14000, artifact: "extracted_sigma_aldrich7" }
          - { start: 14001, end: 16000, artifact: "extracted_sigma_aldrich8" }
          - { start: 16001, end: 18000, artifact: "extracted_sigma_aldrich9" }
          - { start: 18001, end: 20000, artifact: "extracted_sigma_aldrich10" }

    # Pass the matrix values as inputs to the reusable workflow
    with:
      url-start: ${{ matrix.start }}
      url-end: ${{ matrix.end }}
      artifact-name: ${{ matrix.artifact }}
