name: Run ChemFYI

on:
  pull_request:
  workflow_dispatch:

jobs:
  run-chemfyi:
    timeout-minutes: 360
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_READ_ONLY }}

    - name: Run ChemFYI
      id: run_sigma_aldrich
      run: | 
        docker run -v /tmp:/tmp ghcr.io/ryang20718/chemfyi_linux_amd64 main.py --url-start 1 --url-end 2 --batch-size 1

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: extracted_sigma_aldrich
        path: crawled_data_sigma_aldrich/*.md
